server:
  port: 9081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update      
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
 #We used below prop for Config Server /Config Client       
  config:
    import:
    - configserver:http://localhost:9085
        
  application:
    name: USER-SERVICE
        
##We used Config Server /Config Client        
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
       